### ISSUE TITLE
the C header backend emits no cross-package #include, so an emitted header does not compile alone

### ISSUE THREAD

**Issue by stasson** [driftsys/ridl#202]
The extern-C header backend emits no `#include` for cross-package type
references, so an emitted header does not compile on its own. Every package
that names a type from another package is affected.

This is the C-target form of #190. That issue was closed for the Rust and
TypeScript backends; the C header was not part of it.

## Reproduce

```
$ ridlc build crates/ridlc/tests/corpus/veh-cluster --out-dir out --emit c-header
$ grep -oE '\b(ridl_std|veh_common)_[A-Za-z_]+' out/veh.cluster.h | sort | uniq -c
   1 ridl_std_timestamp
   2 veh_common_temperature
$ grep '#include' out/veh.cluster.h
#include <stdbool.h>
#include <stdint.h>
```

Only the two standard-library headers are included. Compiling the emitted
header alone:

```
$ cc -fsyntax-only out/veh.cluster.h
out/veh.cluster.h:45:5: error: unknown type name 'veh_common_temperature'
out/veh.cluster.h:46:5: error: unknown type name 'veh_common_temperature'
```

## Scope

Not specific to `ridl.std`. The first failure above is on an **ordinary**
package, `veh.common`. The gap is that the backend emits no cross-package
include of any kind, so `ridl.std` is simply one instance.

`ridlc build --emit c-header` does now write `ridl.std.h` beside the others
(#200), so the file a header would need to include exists; nothing emits the
include naming it.

## Notes toward a fix

The Rust and TypeScript backends both already record which packages a module
references — the TypeScript one accumulates them in `Ctx::imports` to write its
import lines, and `ridl_ir::v2::referenced_packages` (added in #200) answers
the same question from the IR. Either source gives the include list. The open
question a fix has to settle is the include spelling: the emitted file names are
dotted (`veh.common.h`), so `#include "veh.common.h"` is the direct form, and
whether a consumer is expected to keep that layout is a decision this issue does
not make.

**Comment by stasson** [comment]
Closed as not planned — the defect can no longer occur, because the backend it describes no longer exists.

[ADR-0018](https://github.com/driftsys/ridl/blob/main/docs/decisions/ADR-0018-runtime-core-and-generated-surface.md) decision 6 drops C as a target language, retiring ADR-0007 decision 13. `crates/ridl-backend-rust/src/c_header.rs`, its snapshots, the `Emit::CHeader` variant and the `c-header` CLI value were all removed in `88adafb`, so there is no emitted header to be missing an `#include`. The sibling header issue #236 was closed in the same retraction.

Nothing in the finding carries forward to another target. The Rust backend has no `#include` analogue — a cross-package reference is a path in generated Rust, resolved by the crate graph — and [ADR-0017](https://github.com/driftsys/ridl/blob/main/docs/decisions/ADR-0017-proto3-projection.md) decision 1 gives the proto3 projection its own rule for how a foreign reference projects.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by stasson** [comment]
**Two link corrections to the comment above.**

1. **ADR-0018 is not on `main`** — that link 404s. It is Proposed, in the open draft PR #241: <https://github.com/driftsys/ridl/blob/claude/code-generation-plan-aeyeo8/docs/decisions/ADR-0018-runtime-core-and-generated-surface.md>
2. **ADR-0017's filename is `ADR-0017-proto3-projection-rules.md`**, not `ADR-0017-proto3-projection.md`: <https://github.com/driftsys/ridl/blob/main/docs/decisions/ADR-0017-proto3-projection-rules.md>

The closure itself does not depend on either link. The C header, `Emit::CHeader` and the `c-header` CLI value are gone from the tree as of `88adafb`, so the defect has no code to occur in regardless of whether ADR-0018 is accepted as written. If #241 were rejected and the header restored, this issue should be reopened.

---
_Generated by [Claude Code](https://claude.ai/code)_
